name: run-mats
on: [push]
env:
  CHEZ_BRANCH: v9.5.4
jobs:
  mats:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Chez Scheme ${{ env.CHEZ_BRANCH }}
        working-directory: ${{ runner.temp }}
        shell: bash
        run: |
          git clone --branch $CHEZ_BRANCH --depth 1 --quiet https://github.com/cisco/ChezScheme.git
          cd ChezScheme
          ./configure
          make
          if [ "$RUNNER_OS" = "Windows" ]
          then echo "$PWD/a6nt/bin/a6nt" >> $GITHUB_PATH
          else sudo make install
          fi
      - name: Run mats
        working-directory: ${{ github.workspace }}
        shell: bash
        run: src/run-mats
