name: run-mats
on: [push]
jobs:
  mats:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, ubuntu-24.04, windows-2022]
        chez: [v10.1.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Chez Scheme ${{ matrix.chez }}
        working-directory: ${{ runner.temp }}
        shell: bash
        run: |
          git clone --filter=blob:none --branch ${{ matrix.chez }} --quiet https://github.com/cisco/ChezScheme.git
          cd ChezScheme
          ./configure --nothreads --disable-x11
          make
          if [ "$RUNNER_OS" = "Windows" ]
          then echo "$PWD/a6nt/bin/a6nt" >> $GITHUB_PATH
          else sudo make install
          fi
      - name: Run mats
        working-directory: ${{ github.workspace }}
        shell: bash
        run: src/run-mats
